development: &STANDARD
  build_directory: /data/builds
  # You can uncomment these to enable HTTP Basic Auth.
  # user: user
  # password: password
  
test: &TEST
  build_directory: <%= RAILS_ROOT %>/tmp/spec/builds
  
cucumber:
  <<: *TEST
  
production:
  <<: *STANDARD
