development: &STANDARD
  build_directory: /data/builds
  # You can uncomment these to enable HTTP Basic Auth.
  # user: user
  # password: password
  # email_notifications:
  #   to: test@example.com
  
test: &TEST
  build_directory: <%= RAILS_ROOT %>/tmp/spec/builds
  email_notifications:
    to: "test@example.com"
    from: "ci@example.com"
  
cucumber:
  <<: *TEST
  
production:
  <<: *STANDARD
